# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform qBittorrent installation tasks
  tags:
    - setup-all
    - setup-qbittorrent
    - install-all
    - install-qbittorrent
  block:
    - name: Validate qBittorrent configuration
      when: qbittorrent_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install qBittorrent
      when: qbittorrent_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Get the qBittorrent temporary password
  tags:
    - print-qbittorrent-password
  block:
    - name: Run qBittorrent print temporary password tasks
      when: qbittorrent_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/print_qbittorrent_password.yml"

- name: Perform qBittorrent uninstallation tasks
  tags:
    - setup-all
    - setup-qbittorrent
  block:
    - name: Uninstall qBittorrent
      when: not qbittorrent_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
