# SPDX-FileCopyrightText: 2025 spatterlight
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of qBittorrent systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ qbittorrent_identifier }}.service"
  register: qbittorrent_service_stat

- name: Uninstall qBittorrent systemd services and files
  when: qbittorrent_service_stat.stat.exists | bool
  block:
    - name: Ensure qBittorrent systemd service is stopped
      ansible.builtin.service:
        name: "{{ qbittorrent_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure qBittorrent systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ qbittorrent_identifier }}.service"
        state: absent

    - name: Ensure qBittorrent container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ qbittorrent_container_network }}"
        state: absent

    - name: Ensure qBittorrent container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ qbittorrent_container_network }}
      register: network_deletion_result
      changed_when: qbittorrent_container_network in network_deletion_result.stdout

    - name: Ensure qBittorrent path does not exist
      ansible.builtin.file:
        path: "{{ qbittorrent_base_path }}"
        state: absent
