# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "qbittorrent_container_additional_environment_variables", "new": "qbittorrent_environment_variables_additional_variables" }

- name: Fail if required qBittorrent settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - qbittorrent_uid
    - qbittorrent_gid
    - qbittorrent_hostname

- name: Fail if qBittorrent architecture is not supported
  ansible.builtin.fail:
    msg: >-
      Your configuration specifies a CPU architecture (`{{ qbittorrent_arch }}`) which is not currently supported.
      This qBittorrent role also does not support self-building yet, so it's not possible to make use of it.
  when: "qbittorrent_arch not in ['amd64', 'arm64']"

- name: Validate qBittorrent Traefik configuration
  when: qbittorrent_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required qBittorrent Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - qbittorrent_container_labels_traefik_hostname
        - qbittorrent_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `qbittorrent_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if qbittorrent_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          qbittorrent_container_labels_traefik_path_prefix (`{{ qbittorrent_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/qbittorrent`).
      when: "qbittorrent_container_labels_traefik_path_prefix != '/' and qbittorrent_container_labels_traefik_path_prefix[-1] == '/'"
